name: Gmail Voice Assistant

on:
  workflow_dispatch:   # Run manually from GitHub Actions tab
  push:
    branches:
      - main

jobs:
  run-gmail-assistant:
    runs-on: ubuntu-latest

    steps:
      # Checkout repo
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      # Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install google-api-python-client google-auth-httplib2 google-auth-oauthlib pyttsx3 SpeechRecognition pyaudio

      # Set up credentials.json (from GitHub Secret)
      - name: Create credentials.json
        run: echo "${{ secrets.GMAIL_CREDENTIALS }}" > credentials.json

      # Run the assistant script
      - name: Run Gmail Assistant
        run: python your_script_name.py
